### ISSUE TITLE
separate command line arguments for "from" and "to"

### ISSUE THREAD

**Issue by yairchu** [da-x/git-search-replace#11]
When one does

    git-search-replace colorCount///colourCount

It could be nice to do be able to utilise the shell to do

    git-search-replace colo{,u}rCount

This means replacing (optionally perhaps) the `///` syntax with separate command line arguments for "from" and "to".

**Comment by da-x** [comment]
How about if GSR identified the separator given alone in the command line, it will assume that the next two arguments are the from/to? E.g.:

```
git-search-replace /// colo{,u}rCount
```

We can still have this while preserving the older form, for backward compatibility.

**Comment by yairchu** [comment]
Couldn't it also recognise the format from the number of arguments given?

**Comment by da-x** [comment]
Perhaps, but it would be ambiguous, because the two arguments can two replacement functions, e.g: `a///b c///d`.

**Comment by yairchu** [comment]
Ah, nice feature I didn't know that :)
So I guess `///` could separate different pairs too then - ie

    git-search-replace /// colo{,u}rCount /// fancyColo{,u}r

**Comment by da-x** [comment]
Yep, and it even looks nice :)

**Comment by yairchu** [comment]
One potential problem is if a script calls `git-search-replace` and it replaces the empty string with itself, and then that makes it interpret the next parameters differently.. An alternative without it is just a flag i.e

    git-search-replace -a colo{,u}rCount fancyColo{,u}r

**Comment by da-x** [comment]
Trying to replacing the empty string with itself causes gsr to print all the lines, each N times according to its length. With `-f` and `-d` it's a no-op.

I like the argument option because it preserves the default behavior, plus it's less typing overall. Let's add the argument you suggest and call it `-p`, shortcut for `--pair-arguments`. If given an odd number of arguments, it should print an error (instead of assuming removal). The README.md and help screen should illustrate the shell-reliant use case. Want to try adding it?

**Comment by yairchu** [comment]
> Want to try adding it?

Yeah yalla sure :)

**Comment by da-x** [comment]
Thanks!
