### ISSUE TITLE
colordiff

### ISSUE THREAD

**Issue by eliweis** [da-x/git-search-replace#6]
Add option to use colordiff instead regular diff

**Comment by da-x** [comment]
We filter through the execution of diff, so that the diff emitted turns out to be a valid patch file. `colordiff` however would require emitting straight to the terminal, so we cannot easily use it directly. However, `colordiff` can also add colors to previously emitted diffs that arrive in stdin, so you can do something like:

```
gsr A///B --diff | colordiff
```

And that would work alright. Even consider using `highlight-diff` from `git` for marking the intra-line changes (and it's especially useful with GSR, because it's almost always about intra-line changes).

```
gsr A///B --diff | colordiff | diff-highlight
```

A shell alias `gsrc` would serve it right.

**Comment by da-x** [comment]
Provided externally via [Fancydiff](https://github.com/da-x/fancydiff):
```
gsr A///B -d | fancydiff stdin
```
